### PR TITLE
Beyond PSCC Paper: Post-PSCC Clean-up

### PR DESCRIPTION
**Pull request by timmyfaraday**
notes:
- removed the deprecated folder
- removed the src/server folder
- removed all excess code
- removed iterative approach, will be revisited post contacting Carlton wrt implementing the Metevier paper
- removed the reduced acr implementation as this was proven to be faulty in the pscc paper numerical illustrations
- added code for sampling and kernel density estimation for the resulting variables to enable easier post-processing, removed the plotting code
- remove the util functions to generate stochastic data, choice is made to hard code such data in the m-file
- constraint_voltage_magnitude_bounds is removed
- constraint_bus_theta_ref is renamed to constraint_bus_voltage_ref
- upper limit of the voltage magnitude chance constraint is enforced
- all notions of switches, storage and dc-links are removed and will be added sequentially when tackling such applications

### CODE REVIEW

**Comment by timmyfaraday** [comment]
Next steps:
- [ ] create pg-lib based test files
- [ ] set-up tests
- [ ] add TagBot
- [ ] clean-up import dependencies
- [ ] document novel functionality, including build_stochastic_data, sample and density

**Comment by timmyfaraday** [comment]
@frederikgeth

The test without aux, both with polynomial degree one and two, run through on my personal laptop but fail entirely on the CI, given that the problem does not get solved. Is there a solution for this? Is it possible to exclude certain specific testsets from the CI, with explicit warning that they should be included when testing on your own machine?

**Review by frederikgeth — APPROVED** [review]
looks good to me. will open a few issues for future work

**Comment by timmyfaraday** [comment]
Who uses Ubuntu anyways...

**Pull request merged**
